# Uncomment this line to define a global platform for your project

workspace 'XNGAPIClient'

platform :ios, "7.0"

target "XINGAPISample" do
pod 'XNGAPIClient', :path => 'XNGAPIClient.podspec'
end

target "XINGAPISampleTests" do

end

